//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginInfo
    {
        public int L_id { get; set; }
        public string RealName { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string StaNo { get; set; }
        public string StuNo { get; set; }
        public int Type { get; set; }
        public System.DateTime L_CreateTime { get; set; }
        public int IsDel { get; set; }
        public string Remark { get; set; }
    
        public virtual LoginType LoginType { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Student Student { get; set; }
    }
}
