//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectCourse
    {
        public int SC_id { get; set; }
        public string SC_StudentNo { get; set; }
        public string SC_CourseNo { get; set; }
        public System.DateTime SC_Time { get; set; }
        public int IsDel { get; set; }
    
        public virtual CourseInfo CourseInfo { get; set; }
        public virtual Student Student { get; set; }
    }
}
