//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.ClassInfo = new HashSet<ClassInfo>();
            this.CollegeInfo = new HashSet<CollegeInfo>();
            this.LoginInfo = new HashSet<LoginInfo>();
        }
    
        public int Sta_id { get; set; }
        public string Sta_No { get; set; }
        public string Sta_Name { get; set; }
        public string Sta_Sex { get; set; }
        public System.DateTime Sta_Birthday { get; set; }
        public string Sta_Type { get; set; }
        public string Sta_Telephone { get; set; }
        public string Sta_QQ { get; set; }
        public string Sta_Address { get; set; }
        public System.DateTime Sta_Indate { get; set; }
        public string Sta_Email { get; set; }
        public int IsDel { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassInfo> ClassInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollegeInfo> CollegeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginInfo> LoginInfo { get; set; }
        public virtual StaffType StaffType { get; set; }
    }
}
