//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int ID { get; set; }
        public string S_No { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string IdCard { get; set; }
        public string LandScape { get; set; }
        public string ContactPerson { get; set; }
        public string ContactAddress { get; set; }
        public string ContactNumber { get; set; }
        public string AdmissionNumber { get; set; }
        public string CandidateNumber { get; set; }
        public string Type { get; set; }
        public string Province { get; set; }
        public string Year { get; set; }
        public string ModeAdmission { get; set; }
        public string Reamrk { get; set; }
        public string ImagePath { get; set; }
    }
}
