//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.LoginInfo = new HashSet<LoginInfo>();
            this.Score = new HashSet<Score>();
            this.SelectCourse = new HashSet<SelectCourse>();
        }
    
        public int S_id { get; set; }
        public string S_No { get; set; }
        public string S_Name { get; set; }
        public string S_Sex { get; set; }
        public System.DateTime S_Birthday { get; set; }
        public string S_ClassNo { get; set; }
        public string S_Telephone { get; set; }
        public string S_QQ { get; set; }
        public string S_Address { get; set; }
        public System.DateTime S_Indate { get; set; }
        public string S_Email { get; set; }
        public int IsDel { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginInfo> LoginInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Score { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectCourse> SelectCourse { get; set; }
        public virtual Student Student1 { get; set; }
        public virtual Student Student2 { get; set; }
    }
}
